// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package example

type iMapper interface {
	// ToUser converts a UserEntity value into a User value.
	ToUser(in UserEntity) User

	// FromUser converts a User value into a UserEntity value.
	FromUser(in User) UserEntity
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToUser(in UserEntity) User {
	var out User

	out.ID = in.ID
	out.Email = in.Email

	return out
}

func (m *iMapperImpl) FromUser(in User) UserEntity {
	var out UserEntity

	out.ID = in.ID
	out.Email = in.Email

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
