// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package rest

import domain "github.com/toniphan21/go-mapper-gen/config/domain"

type iMapper interface {
	// ToAddressResponse converts a domain.Address value into a AddressResponse value.
	ToAddressResponse(in domain.Address) AddressResponse

	// FromAddressResponse converts a AddressResponse value into a domain.Address
	// value.
	FromAddressResponse(in AddressResponse) domain.Address

	// ToUserResponse converts a domain.User value into a UserResponse value.
	ToUserResponse(in domain.User) UserResponse

	// FromUserResponse converts a UserResponse value into a domain.User value.
	FromUserResponse(in UserResponse) domain.User
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToAddressResponse(in domain.Address) AddressResponse {
	var out AddressResponse

	out.ID = in.ID
	out.HouseNumber = in.HouseNumber
	out.Street = in.Street
	out.City = in.City
	out.State = in.State
	out.Country = in.Country

	return out
}

func (m *iMapperImpl) FromAddressResponse(in AddressResponse) domain.Address {
	var out domain.Address

	out.ID = in.ID
	out.HouseNumber = in.HouseNumber
	out.Street = in.Street
	out.City = in.City
	out.State = in.State
	out.Country = in.Country

	return out
}

func (m *iMapperImpl) ToUserResponse(in domain.User) UserResponse {
	var out UserResponse

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email
	out.Age = in.Age

	return out
}

func (m *iMapperImpl) FromUserResponse(in UserResponse) domain.User {
	var out domain.User

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email
	out.Age = in.Age

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
