// Code generated by github.com/toniphan21/go-mapper-gen - v1.0.0, DO NOT EDIT.

package grpc

type iMapper interface {
	// ToUser converts a UserMessage value into a User value.
	ToUser(in UserMessage) User

	// FromUser converts a User value into a UserMessage value.
	FromUser(in User) UserMessage
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToUser(in UserMessage) User {
	var out User

	out.Email = in.Email
	out.ID = in.Id
	out.Password = in.Password

	return out
}

func (m *iMapperImpl) FromUser(in User) UserMessage {
	var out UserMessage

	out.Email = in.Email
	out.Id = in.ID
	out.Password = in.Password

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
