// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package example

import pgtype "github.com/jackc/pgx/v5/pgtype"

type iMapper interface {
	// ToDomain converts a Database value into a Domain value.
	ToDomain(in Database) Domain

	// FromDomain converts a Domain value into a Database value.
	FromDomain(in Domain) Database
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToDomain(in Database) Domain {
	var out Domain

	if in.A.Valid {
		out.A = &in.A.Bool
	}

	var v0 *bool
	if in.B.Valid {
		v0 = &in.B.Bool
	}
	if v0 != nil {
		out.B = *v0
	} else {
		var zero bool
		out.B = zero
	}

	return out
}

func (m *iMapperImpl) FromDomain(in Domain) Database {
	var out Database

	if in.A != nil {
		out.A = pgtype.Bool{
			Bool:  *in.A,
			Valid: true,
		}
	}

	var v0 *bool
	v0 = &in.B
	if v0 != nil {
		out.B = pgtype.Bool{
			Bool:  *v0,
			Valid: true,
		}
	}

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
