// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package grpc

import gmglib "github.com/toniphan21/gmg-lib/gen/go/iam/v1"
import timestamppb "google.golang.org/protobuf/types/known/timestamppb"

type iMapper interface {
	// ToUser converts a User value into a User value.
	ToUser(in gmglib.User) User

	// FromUser converts a User value into a User value.
	FromUser(in User) gmglib.User
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToUser(in gmglib.User) User {
	var out User

	out.Name = in.Name
	out.ID = in.ID
	out.Age = in.Age
	out.Email = in.Email
	out.UpdatedAt = in.UpdatedAt.ToTime()
	out.CreatedAt = in.CreatedAt.ToTime()

	return out
}

func (m *iMapperImpl) FromUser(in User) gmglib.User {
	var out gmglib.User

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email
	out.Age = in.Age
	out.CreatedAt = timestamppb.Timestamp{
		Seconds: int64(in.CreatedAt.Unix()),
		Nanos: int32(in.CreatedAt.Nanosecond()),
	}
	out.UpdatedAt = timestamppb.Timestamp{
		Seconds: int64(in.UpdatedAt.Unix()),
		Nanos: int32(in.UpdatedAt.Nanosecond()),
	}

	return out
}

var _ iMapper = (*iMapperImpl)(nil)