package gomappergen

import (
	"fmt"
	"path/filepath"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

const BinaryName = "github.com/toniphan21/go-mapper-gen"

var version = "v0.4.0"

func UseTestVersion() {
	version = "test"
}

func Version() string {
	return version
}

type FileManager interface {
	MakeJenFile(parser Parser, currentPkg *packages.Package, config PackageConfig) *jen.File

	JenFiles() map[string]*jen.File
}

func DefaultFileManager() FileManager {
	return &fileManagerImpl{
		version: version,
		files:   make(map[string]*jen.File),
	}
}

type fileManagerImpl struct {
	version string
	files   map[string]*jen.File
}

func (fm *fileManagerImpl) JenFiles() map[string]*jen.File {
	return fm.files
}

func (fm *fileManagerImpl) MakeJenFile(parser Parser, currentPkg *packages.Package, config PackageConfig) *jen.File {
	target := filepath.Join(currentPkg.Dir, config.Output.FileName)
	fullPath, err := filepath.Rel(parser.SourceDir(), target)
	if err != nil {
		panic(err)
	}

	v, have := fm.files[fullPath]
	if have {
		return v
	}

	pkgName := replacePlaceholders(config.Output.PkgName, map[string]string{
		Placeholder.CurrentPackageName: currentPkg.Name,
	})

	jf := jen.NewFilePathName(currentPkg.PkgPath, pkgName)
	jf.HeaderComment(fmt.Sprintf("Code generated by %v - %v, DO NOT EDIT.", BinaryName, fm.version))
	fm.files[fullPath] = jf

	return jf
}

var _ FileManager = (*fileManagerImpl)(nil)
