package gomappergen

import (
	"fmt"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

const BinaryName = "github.com/toniphan21/go-mapper-gen"

var version = "0.1.0"

func Version() string {
	return version
}

type FileManager interface {
	MakeJenFile(currentPkg *packages.Package, config Config) *jen.File

	JenFiles() map[string]*jen.File
}

func DefaultFileManager() FileManager {
	return defaultFileManager(Version())
}

func defaultFileManager(version string) FileManager {
	return &fileManagerImpl{
		version: version,
		files:   make(map[string]*jen.File),
	}
}

type fileManagerImpl struct {
	version string
	files   map[string]*jen.File
}

func (fm *fileManagerImpl) JenFiles() map[string]*jen.File {
	return fm.files
}

func (fm *fileManagerImpl) MakeJenFile(currentPkg *packages.Package, config Config) *jen.File {
	v, have := fm.files[config.Output.FileName]
	if have {
		return v
	}

	pkgName := replacePlaceholders(config.Output.PkgName, map[string]string{
		Placeholder.CurrentPackageName: currentPkg.Name,
	})

	jf := jen.NewFilePathName(currentPkg.PkgPath, pkgName)
	jf.HeaderComment(fmt.Sprintf("Code generated by %v - %v, DO NOT EDIT.", BinaryName, fm.version))
	fm.files[config.Output.FileName] = jf

	return jf
}

var _ FileManager = (*fileManagerImpl)(nil)
