package gomappergen

import (
	"fmt"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

type FileManager interface {
	MakeJenFile(currentPkg *packages.Package, config Config) *jen.File

	JenFiles() map[string]*jen.File
}

func DefaultFileManager(binary, version string) FileManager {
	return &defaultFileManager{
		binary:  binary,
		version: version,
		files:   make(map[string]*jen.File),
	}
}

type defaultFileManager struct {
	binary  string
	version string
	files   map[string]*jen.File
}

func (fm *defaultFileManager) JenFiles() map[string]*jen.File {
	return fm.files
}

func (fm *defaultFileManager) MakeJenFile(currentPkg *packages.Package, config Config) *jen.File {
	v, have := fm.files[config.Output.FileName]
	if have {
		return v
	}

	pkgName := replacePlaceholders(config.Output.PkgName, map[string]string{
		Placeholder.CurrentPackageName: currentPkg.Name,
	})

	jf := jen.NewFilePathName(currentPkg.PkgPath, pkgName)
	jf.HeaderComment(fmt.Sprintf("Code generated by %v - %v, DO NOT EDIT.", fm.binary, fm.version))
	fm.files[config.Output.FileName] = jf

	return jf
}

var _ FileManager = (*defaultFileManager)(nil)
