// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package basic

type Mapper interface {
	// ToUser converts a UserEntity value into a User value.
	ToUser(in UserEntity) User

	// FromUser converts a User value into a UserEntity value.
	FromUser(in User) UserEntity
}

func NewMapper() Mapper {
	return &mapperImpl{}
}

type mapperImpl struct{}

func (m *mapperImpl) ToUser(in UserEntity) User {
	var out User

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email
	out.Age = in.Age

	return out
}

func (m *mapperImpl) FromUser(in User) UserEntity {
	var out UserEntity

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email
	out.Age = in.Age

	return out
}

var _ Mapper = (*mapperImpl)(nil)
