// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package example

import (
	v1 "github.com/toniphan21/gmg-lib/gen/go/iam/v1"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

type iMapper interface {
	// ToUser converts a iamV1.User value into a User value.
	ToUser(in v1.User) User

	// FromUser converts a User value into a iamV1.User value.
	FromUser(in User) v1.User
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToUser(in v1.User) User {
	var out User

	out.ID = in.Id
	out.Age = in.Age
	out.LastName = in.LastName
	out.FirstName = in.FirstName
	out.Email = in.Email

	var v0 time.Time
	if in.UpdatedAt != nil {
		v0 = in.UpdatedAt.AsTime()
	}
	out.UpdatedAt = &v0

	var v1 time.Time
	if in.CreatedAt != nil {
		v1 = in.CreatedAt.AsTime()
	}
	out.CreatedAt = &v1

	return out
}

func (m *iMapperImpl) FromUser(in User) v1.User {
	var out v1.User

	out.Id = in.ID
	out.FirstName = in.FirstName
	out.LastName = in.LastName
	out.Email = in.Email
	out.Age = in.Age

	var v0 time.Time
	if in.CreatedAt != nil {
		v0 = *in.CreatedAt
	}
	out.CreatedAt = timestamppb.New(v0)

	var v1 time.Time
	if in.UpdatedAt != nil {
		v1 = *in.UpdatedAt
	}
	out.UpdatedAt = timestamppb.New(v1)

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
