// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package decorator

type iMapper interface {
	// ToUser converts a UserMessage value into a User value.
	ToUser(in UserMessage) User

	// FromUser converts a User value into a UserMessage value.
	FromUser(in User) UserMessage
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToUser(in UserMessage) User {
	var out User

	out.ID = in.ID
	out.Name = in.Name

	return out
}

func (m *iMapperImpl) FromUser(in User) UserMessage {
	var out UserMessage

	out.ID = in.ID
	out.Name = in.Name

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
