// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package rest

import domain "github.com/toniphan21/go-mapper-gen/config/domain"

type iMapper interface {
	// CreateAddressResponse converts a domain.Address value into a AddressResponse
	// value.
	CreateAddressResponse(in domain.Address) AddressResponse

	// ToAddress converts a AddressResponse value into a domain.Address value.
	ToAddress(in AddressResponse) domain.Address

	// MakeUserResponse converts a domain.User value into a UserResponse value.
	MakeUserResponse(in domain.User) UserResponse

	// ConvertToUser converts a UserResponse value into a domain.User value.
	ConvertToUser(in UserResponse) domain.User
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) CreateAddressResponse(in domain.Address) AddressResponse {
	var out AddressResponse

	out.ID = in.ID
	out.HouseNumber = in.HouseNumber
	out.Street = in.Street
	out.City = in.City
	out.State = in.State
	out.Country = in.Country

	return out
}

func (m *iMapperImpl) ToAddress(in AddressResponse) domain.Address {
	var out domain.Address

	out.ID = in.ID
	out.HouseNumber = in.HouseNumber
	out.Street = in.Street
	out.City = in.City
	out.State = in.State
	out.Country = in.Country

	return out
}

func (m *iMapperImpl) MakeUserResponse(in domain.User) UserResponse {
	var out UserResponse

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email
	out.Age = in.Age

	return out
}

func (m *iMapperImpl) ConvertToUser(in UserResponse) domain.User {
	var out domain.User

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email
	out.Age = in.Age

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
