// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package decorator

// ToUser converts a UserMessage value into a User value.
func ToUser(in UserMessage) User {
	var out User

	out.ID = in.ID
	out.Name = in.Name

	return out
}

// FromUser converts a User value into a UserMessage value.
func FromUser(in User) UserMessage {
	var out UserMessage

	out.ID = in.ID
	out.Name = in.Name

	return out
}
