// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package decorator

// ToUser converts a UserEntity value into a User value.
func ToUser(in UserEntity) User {
	var out User

	out.ID = in.ID

	// Fields that could not be mapped:
	// out.Name =

	return out
}

// FromUser converts a User value into a UserEntity value.
func FromUser(in User) UserEntity {
	var out UserEntity

	out.ID = in.ID

	// Fields that could not be mapped:
	// out.Email =

	return out
}
