// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package example

import gmglib "github.com/toniphan21/gmg-lib"

type iMapper interface {
	// ToUser converts a gmg.User value into a User value.
	ToUser(in gmglib.User) User

	// FromUser converts a User value into a gmg.User value.
	FromUser(in User) gmglib.User
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToUser(in gmglib.User) User {
	var out User

	out.Name = in.Name
	out.ID = in.ID
	out.Age = in.Age
	out.Email = in.Email
	out.UpdatedAt = in.UpdatedAt
	out.CreatedAt = in.CreatedAt

	return out
}

func (m *iMapperImpl) FromUser(in User) gmglib.User {
	var out gmglib.User

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email
	out.Age = in.Age
	out.CreatedAt = in.CreatedAt
	out.UpdatedAt = in.UpdatedAt

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
