// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package numeric

type iMapper interface {
	// ToTarget converts a Source value into a Target value.
	ToTarget(in Source) Target

	// FromTarget converts a Target value into a Source value.
	FromTarget(in Target) Source
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToTarget(in Source) Target {
	var out Target

	out.A = uint(in.A)
	out.B = uint(in.B)
	out.C = uint(in.C)
	out.D = uint(in.D)
	out.E = uint(in.E)
	out.F = uint(in.F)
	out.G = uint(in.G)
	out.H = uint(in.H)
	out.I = uint(in.I)
	out.J = in.J
	out.K = uint(in.K)
	out.L = uint(in.L)
	out.M = uint(in.M)
	out.N = uint(in.N)
	out.O = in.O

	return out
}

func (m *iMapperImpl) FromTarget(in Target) Source {
	var out Source

	out.A = byte(in.A)
	out.B = uint8(in.B)
	out.C = uint16(in.C)
	out.D = uint32(in.D)
	out.E = uint64(in.E)
	out.F = int8(in.F)
	out.G = int16(in.G)
	out.H = int32(in.H)
	out.I = int64(in.I)
	out.J = in.J
	out.K = int(in.K)
	out.L = float32(in.L)
	out.M = float64(in.M)
	out.N = Typed(in.N)
	out.O = in.O

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
