// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package decorator

type iMapper interface {
	// ToUser converts a UserMessage value into a User value.
	ToUser(in UserMessage) User

	// FromUser converts a User value into a UserMessage value.
	FromUser(in User) UserMessage
}

type iMapperDecorator interface {
	decorateToUser(in *UserMessage, out *User)

	decorateFromUser(in *User, out *UserMessage)
}

func new_iMapper(decorator iMapperDecorator) iMapper {
	return &iMapperImpl{decorator: decorator}
}

type iMapperImpl struct {
	decorator iMapperDecorator
}

func (m *iMapperImpl) ToUser(in UserMessage) User {
	var out User

	out.ID = in.ID
	out.Name = in.Name

	if m.decorator != nil {
		m.decorator.decorateToUser(&in, &out)
	}

	return out
}

func (m *iMapperImpl) FromUser(in User) UserMessage {
	var out UserMessage

	out.ID = in.ID
	out.Name = in.Name

	if m.decorator != nil {
		m.decorator.decorateFromUser(&in, &out)
	}

	return out
}

type iMapperDecoratorNoOp struct{}

func (d *iMapperDecoratorNoOp) decorateToUser(in *UserMessage, out *User) {}

func (d *iMapperDecoratorNoOp) decorateFromUser(in *User, out *UserMessage) {}

var _ iMapper = (*iMapperImpl)(nil)
var _ iMapperDecorator = (*iMapperDecoratorNoOp)(nil)
