// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package example

import pgtype "github.com/jackc/pgx/v5/pgtype"

type iMapper interface {
	// ToDomain converts a Database value into a Domain value.
	ToDomain(in Database) Domain

	// FromDomain converts a Domain value into a Database value.
	FromDomain(in Domain) Database
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToDomain(in Database) Domain {
	var out Domain

	if in.A.Valid {
		out.A = &in.A.Int64
	}

	var v0 *int64
	if in.B.Valid {
		v0 = &in.B.Int64
	}
	if v0 != nil {
		out.B = *v0
	} else {
		var zero int64
		out.B = zero
	}

	var v1 *int64
	if in.C.Valid {
		v1 = &in.C.Int64
	}

	var v2 int64
	if v1 != nil {
		v2 = *v1
	}
	out.C = int(v2)

	return out
}

func (m *iMapperImpl) FromDomain(in Domain) Database {
	var out Database

	if in.A != nil {
		out.A = pgtype.Int8{
			Int64: *in.A,
			Valid: true,
		}
	}

	var v0 *int64
	v0 = &in.B
	if v0 != nil {
		out.B = pgtype.Int8{
			Int64: *v0,
			Valid: true,
		}
	}

	var v1 *int64
	v2 := int64(in.C)
	v1 = &v2

	if v1 != nil {
		out.C = pgtype.Int8{
			Int64: *v1,
			Valid: true,
		}
	}

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
