// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package fc

type iMapper interface {
	// ToTarget converts a Source value into a Target value.
	ToTarget(in Source) Target

	// FromTarget converts a Target value into a Source value.
	FromTarget(in Target) Source
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToTarget(in Source) Target {
	var out Target

	out.ID = StringToMyID(in.ID)
	out.Name = in.Name

	return out
}

func (m *iMapperImpl) FromTarget(in Target) Source {
	var out Source

	out.ID = MyIDToString(in.ID)
	out.Name = in.Name

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
