// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package domain

type iMapper1 interface {
	ToMultipleMapperTarget(in MultipleMapperSource) MultipleMapperTarget

	FromMultipleMapperTarget(in MultipleMapperTarget) MultipleMapperSource
}

type iMapper1Impl struct{}

func (m *iMapper1Impl) ToMultipleMapperTarget(in MultipleMapperSource) MultipleMapperTarget {
	var out MultipleMapperTarget

	if in.ID == nil {
		var zero string
		out.ID = zero
	} else {
		out.ID = *in.ID
	}

	return out
}

func (m *iMapper1Impl) FromMultipleMapperTarget(in MultipleMapperTarget) MultipleMapperSource {
	var out MultipleMapperSource

	out.ID = &in.ID

	return out
}

var _ iMapper1 = (*iMapper1Impl)(nil)

type iMapper2 interface {
	// ToMultipleMapperTarget converts a MultipleMapperSource value into a
	// MultipleMapperTarget value.
	ToMultipleMapperTarget(in MultipleMapperSource) MultipleMapperTarget

	// FromMultipleMapperTarget converts a MultipleMapperTarget value into a
	// MultipleMapperSource value.
	FromMultipleMapperTarget(in MultipleMapperTarget) MultipleMapperSource
}

type iMapper2Impl struct{}

func (m *iMapper2Impl) ToMultipleMapperTarget(in MultipleMapperSource) MultipleMapperTarget {
	var out MultipleMapperTarget

	if in.ID == nil {
		var zero string
		out.ID = zero
	} else {
		out.ID = *in.ID
	}

	return out
}

func (m *iMapper2Impl) FromMultipleMapperTarget(in MultipleMapperTarget) MultipleMapperSource {
	var out MultipleMapperSource

	out.ID = &in.ID

	return out
}

var _ iMapper2 = (*iMapper2Impl)(nil)

type iMapper3 interface {
	// ToMultipleMapperTarget converts a MultipleMapperSource value into a
	// MultipleMapperTarget value.
	ToMultipleMapperTarget(in MultipleMapperSource) MultipleMapperTarget

	// FromMultipleMapperTarget converts a MultipleMapperTarget value into a
	// MultipleMapperSource value.
	FromMultipleMapperTarget(in MultipleMapperTarget) MultipleMapperSource
}

type iMapper3Impl struct{}

func (m *iMapper3Impl) ToMultipleMapperTarget(in MultipleMapperSource) MultipleMapperTarget {
	var out MultipleMapperTarget

	if in.ID == nil {
		var zero string
		out.ID = zero
	} else {
		out.ID = *in.ID
	}

	return out
}

func (m *iMapper3Impl) FromMultipleMapperTarget(in MultipleMapperTarget) MultipleMapperSource {
	var out MultipleMapperSource

	out.ID = &in.ID

	return out
}

var _ iMapper3 = (*iMapper3Impl)(nil)
