// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package numeric

type iMapper interface {
	// ToTarget converts a Source value into a Target value.
	ToTarget(in Source) Target

	// FromTarget converts a Target value into a Source value.
	FromTarget(in Target) Source
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToTarget(in Source) Target {
	var out Target

	out.A = int(in.A)

	var v0 uint
	if in.B != nil {
		v0 = *in.B
	}
	out.B = int(v0)
	v1 := int(in.C)
	out.C = &v1

	var v2 uint
	if in.D != nil {
		v2 = *in.D
	}
	v3 := int(v2)
	out.D = &v3

	return out
}

func (m *iMapperImpl) FromTarget(in Target) Source {
	var out Source

	out.A = uint(in.A)
	v0 := uint(in.B)
	out.B = &v0

	var v1 int
	if in.C != nil {
		v1 = *in.C
	}
	out.C = uint(v1)

	var v2 int
	if in.D != nil {
		v2 = *in.D
	}
	v3 := uint(v2)
	out.D = &v3

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
