// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package multimappers

type iMapper interface {
	ToUser(in UserEntity) User

	FromUser(in User) UserEntity
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToUser(in UserEntity) User {
	var out User

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email

	// Fields that could not be mapped:
	// out.Age =

	return out
}

func (m *iMapperImpl) FromUser(in User) UserEntity {
	var out UserEntity

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email

	return out
}

var _ iMapper = (*iMapperImpl)(nil)

type Mapper interface {
	// ToUser converts a UserEntity value into a User value.
	ToUser(in UserEntity) User

	// FromUser converts a User value into a UserEntity value.
	FromUser(in User) UserEntity
}

type MapperDecorator interface {
	decorateToUser(in *UserEntity, out *User)

	decorateFromUser(in *User, out *UserEntity)
}

func NewMapper(decorator MapperDecorator) Mapper {
	return &mapperImpl{decorator: decorator}
}

type mapperImpl struct {
	decorator MapperDecorator
}

func (m *mapperImpl) ToUser(in UserEntity) User {
	var out User

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email

	if m.decorator != nil {
		m.decorator.decorateToUser(&in, &out)
	}

	return out
}

func (m *mapperImpl) FromUser(in User) UserEntity {
	var out UserEntity

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email

	if m.decorator != nil {
		m.decorator.decorateFromUser(&in, &out)
	}

	return out
}

type MapperDecoratorNoOp struct{}

func (d *MapperDecoratorNoOp) decorateToUser(in *UserEntity, out *User) {
	// Fields that could not be mapped:
	// out.Age =
}

func (d *MapperDecoratorNoOp) decorateFromUser(in *User, out *UserEntity) {}

var _ Mapper = (*mapperImpl)(nil)
var _ MapperDecorator = (*MapperDecoratorNoOp)(nil)

// ToUser converts a UserEntity value into a User value.
func ToUser(in UserEntity, decorators ...func(*UserEntity, *User)) User {
	var out User

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email

	// Fields that could not be mapped:
	// out.Age =

	for _, decorate := range decorators {
		decorate(&in, &out)
	}

	return out
}

// FromUser converts a User value into a UserEntity value.
func FromUser(in User) UserEntity {
	var out UserEntity

	out.ID = in.ID
	out.Name = in.Name
	out.Email = in.Email

	return out
}
