// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package mapping

type iMapper interface {
	// ToTarget converts a Source value into a Target value.
	ToTarget(in Source) Target

	// FromTarget converts a Target value into a Source value.
	FromTarget(in Target) Source
}

type iMapperDecorator interface {
	decorateToTarget(in *Source, out *Target)

	decorateFromTarget(in *Target, out *Source)
}

func new_iMapper(decorator iMapperDecorator) iMapper {
	return &iMapperImpl{decorator: decorator}
}

type iMapperImpl struct {
	decorator iMapperDecorator
}

func (m *iMapperImpl) ToTarget(in Source) Target {
	var out Target

	out.Email = in.Email

	if m.decorator != nil {
		m.decorator.decorateToTarget(&in, &out)
	}

	return out
}

func (m *iMapperImpl) FromTarget(in Target) Source {
	var out Source

	out.Email = in.Email

	if m.decorator != nil {
		m.decorator.decorateFromTarget(&in, &out)
	}

	return out
}

type iMapperDecoratorNoOp struct{}

func (d *iMapperDecoratorNoOp) decorateToTarget(in *Source, out *Target) {
	// Fields that could not be mapped:
	// out.ID =
	// out.FirstName =
	// out.LastName =
}

func (d *iMapperDecoratorNoOp) decorateFromTarget(in *Target, out *Source) {
	// Fields that could not be mapped:
	// out.Id =
	// out.Surname =
	// out.GivenName =
}

var _ iMapper = (*iMapperImpl)(nil)
var _ iMapperDecorator = (*iMapperDecoratorNoOp)(nil)
