// Code generated by github.com/toniphan21/go-mapper-gen - test, DO NOT EDIT.

package example

import db "github.com/toniphan21/go-mapper-gen/example/db"

type iMapper interface {
	// ToUser converts a db.UserEntity value into a User value.
	ToUser(in db.UserEntity) User

	// FromUser converts a User value into a db.UserEntity value.
	FromUser(in User) db.UserEntity
}

func new_iMapper() iMapper {
	return &iMapperImpl{}
}

type iMapperImpl struct{}

func (m *iMapperImpl) ToUser(in db.UserEntity) User {
	var out User

	out.ID = in.ID
	out.Email = in.Email

	return out
}

func (m *iMapperImpl) FromUser(in User) db.UserEntity {
	var out db.UserEntity

	out.ID = in.ID
	out.Email = in.Email

	return out
}

var _ iMapper = (*iMapperImpl)(nil)
